### ISSUE TITLE
An error occurred while loading the archive

### ISSUE THREAD

**Issue by joseph2mi** [EtienneAb3d/WhisperTimeSync#10]
"An error occurred while loading the archive"

I got this error when trying to download the ComPair.exe for cross-lingual alignment. It would not start. Is there a fix? Thank you.

**Comment by EtienneAb3d** [comment]
What browser did you use to download? 
I got some trouble downloading with Firefox. Possible a problem with my hosting.
Can you try with an other one?

**Comment by joseph2mi** [comment]
I used Google Chrome. It downloaded normally, but it wouldn't start

**Comment by EtienneAb3d** [comment]
@joseph2mi 
I just got it downloaded and installed without trouble.
What link did you use?
Can you try to download it again with an other browser?

**Comment by joseph2mi** [comment]
It worked. I downloaded with Microsoft Edge and it had an option to not block the file since it was downloaded from a website it was unsure about. I think the other browsers automatically block it due to where it's being downloaded from.
