### ISSUE TITLE
Synchronization offset

### ISSUE THREAD

**Issue by skittlesvampir** [EtienneAb3d/WhisperTimeSync#14]
Problem description: https://github.com/openai/whisper/discussions/1770#discussioncomment-7526482

I've uploaded the data at: https://ben.ist-toll.xyz/k/whisper-test-files/

**Comment by EtienneAb3d** [comment]
@skittlesvampir 
Bug fixed: when the accurate text is also in SRT format, both timestamps were in ouput
🙃

**Comment by skittlesvampir** [comment]
Oh my god, now it works!! Thank you so much.

Just two small details:

1. The Whisper subtitles often quite long compared to the original subtitle that is broken into smaller pieces. (Screenshot 1) Is there a way to get shorter segments?
2. Sometimes, lot's of consecutive subtitles are combined into a single subtitle (Screenshot 2), because Whisper didn't detect anything for a while. Would it be possible to approximate the subtitles in-between using framerates or something like that?


![mpv-shot0002](https://github.com/EtienneAb3d/WhisperTimeSync/assets/62459226/f070bacc-35c7-4927-b353-3a6b812aa37d) Screenshot 1

![mpv-shot0001](https://github.com/EtienneAb3d/WhisperTimeSync/assets/62459226/4510e41c-dc40-4b68-af20-a80f8b09121c) Screenshot 2

**Comment by EtienneAb3d** [comment]
I think it would be very hard to do a good job when guessing timestamps interpolations. In-between texts could be partially fast or slow and may include some sub-parts without spoken text.

For point 2: the real solution is to improve the Whisper recognition. This can be obtained with WhisperHallu.
https://github.com/EtienneAb3d/WhisperHallu

For both points 1 and 2: I'm currently working on a solution using  word-level timestamps and some complementary pre-/post-processing around WhisperHallu. I don't plan to release it fully open-source. We can discuss about it if you have a budget.

**Comment by skittlesvampir** [comment]
I will check WhisperHallu out, it seems cool.

Unfortunately, I don't have a budget, I'm just synchronizing my own shows so I can understand them better.

Anyways, I think the errors are acceptable, so thank you for your work! I wish your business much success in the future!
