### ISSUE TITLE
License

### ISSUE THREAD

**Issue by afishhh** [EtienneAb3d/WhisperTimeSync#16]
Hello, I'd love to use your token synchronization algorithm in a version of this project updated to work with a specialized tokenizer to support Asian languages. The issue is that currently I am unable to find a license for this project which means [I cannot do this](https://choosealicense.com/no-permission/). Therefore I want to ask whether you can license this code under a permissive enough license to allow others to improve on it and utilize it in other projects.

update: I found a better solution for my own use cases, but I guess I'll leave this issue open as someone may still want to use this project in derivative works.

**Comment by EtienneAb3d** [comment]
@afishhh 
Consider that WhisperTimeSync  is provided with a "do what you want with it at your own risk" license.

**Comment by afishhh** [comment]
Thank you for the clarification, I won't have to reinvent the wheel with the alignment scoring now.
Maybe consider adding such a disclaimer into the readme or better yet add something like Unlicense as a LICENSE file to make your intent clearer.
Since I think my issue has theoretically been solved though I'm going to close this.
