### ISSUE TITLE
how can I change language option to  transcribe audio 

### ISSUE THREAD

**Issue by artistry01** [EtienneAb3d/WhisperTimeSync#4]
You example is excellent but if i want to  transcribe audio  non-English (it is not automatically detected ), what should I add  before or after? 

 !nvidia-smi
!python3 WhisperTimeSync/transcribe.py WhisperTimeSync/data/[ ].mp3 large

**Comment by EtienneAb3d** [comment]
@artistry01,
This `transcribe.py` script is just an example to show a standard use of Whisper.  You need to adapt it to your need according to the Whisper API. For the language option, see the `decode_options` here:
https://github.com/openai/whisper/blob/c09a7ae299c4c34c5839a76380ae407e7d785914/whisper/transcribe.py#L109

You may also use/adapt this code with some more ready-to-use options and additional processing:
https://github.com/EtienneAb3d/WhisperHallu

**Comment by artistry01** [comment]
I got it! Thank very much!
